package com.safety.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
public class Hotspot {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    // VIEWPOINT, REST_STOP, MEDICAL, WATER, SHELTER, DANGER_CLUSTER
    private String category;

    private double latitude;
    private double longitude;

    // Radius in metres — used for "tourists nearby" detection
    private double radius = 100;

    @Column(length = 1000)
    private String description;

    // Comma-separated list: "Toilets,Parking,First Aid"
    private String facilities;

    private Integer capacity;

    // true = auto-generated by clustering algorithm
    private boolean autoGenerated = false;

    // Cached count of alerts that occurred within radius
    private int alertCount = 0;

    private String openingTime;   // e.g. "06:00"
    private String closingTime;   // e.g. "18:00"
    private String breakStart;    // e.g. "13:00"
    private String breakEnd;      // e.g. "14:00"
    private String openDays;      // e.g. "Mon-Sun"
    private LocalDateTime createdAt;

    public Hotspot() {}

    // Getters & setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public double getLatitude() { return latitude; }
    public void setLatitude(double latitude) { this.latitude = latitude; }

    public double getLongitude() { return longitude; }
    public void setLongitude(double longitude) { this.longitude = longitude; }

    public double getRadius() { return radius; }
    public void setRadius(double radius) { this.radius = radius; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getFacilities() { return facilities; }
    public void setFacilities(String facilities) { this.facilities = facilities; }

    public Integer getCapacity() { return capacity; }
    public void setCapacity(Integer capacity) { this.capacity = capacity; }

    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public int getAlertCount() { return alertCount; }
    public void setAlertCount(int alertCount) { this.alertCount = alertCount; }

    public String getOpeningTime() { return openingTime; }
    public void setOpeningTime(String t) { this.openingTime = t; }
    public String getClosingTime() { return closingTime; }
    public void setClosingTime(String t) { this.closingTime = t; }
    public String getBreakStart() { return breakStart; }
    public void setBreakStart(String t) { this.breakStart = t; }
    public String getBreakEnd() { return breakEnd; }
    public void setBreakEnd(String t) { this.breakEnd = t; }
    public String getOpenDays() { return openDays; }
    public void setOpenDays(String d) { this.openDays = d; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
