package com.safety.controller;

import com.safety.model.Alert;
import com.safety.model.Hotspot;
import com.safety.model.HotspotReview;
import com.safety.model.LocationHistory;
import com.safety.model.Tourist;
import com.safety.repository.AlertRepository;
import com.safety.repository.HotspotRepository;
import com.safety.repository.HotspotReviewRepository;
import com.safety.repository.LocationHistoryRepository;
import com.safety.repository.TouristRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.*;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/hotspots")
public class HotspotController {

    @Autowired private HotspotRepository             hotspotRepository;
    @Autowired private AlertRepository               alertRepository;
    @Autowired private LocationHistoryRepository     locationHistoryRepository;
    @Autowired private TouristRepository             touristRepository;
    @Autowired private HotspotReviewRepository       reviewRepository;

    @GetMapping
    public ResponseEntity<List<Hotspot>> getAll() {
        return ResponseEntity.ok(hotspotRepository.findAll());
    }

    @PostMapping
    public ResponseEntity<Hotspot> create(@RequestBody Hotspot hotspot) {
        hotspot.setCreatedAt(LocalDateTime.now(ZoneId.of("Asia/Kolkata")));
        hotspot.setAutoGenerated(false);
        return ResponseEntity.ok(hotspotRepository.save(hotspot));
    }

    @PutMapping("/{id}")
    public ResponseEntity<Hotspot> update(@PathVariable Long id, @RequestBody Hotspot hotspot) {
        hotspot.setId(id);
        return ResponseEntity.ok(hotspotRepository.save(hotspot));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        hotspotRepository.deleteById(id);
        return ResponseEntity.noContent().build();
    }

    @GetMapping("/{id}/nearby-tourists")
    public ResponseEntity<List<Map<String, Object>>> getNearbyTourists(@PathVariable Long id) {
        Hotspot h = hotspotRepository.findById(id).orElse(null);
        if (h == null) return ResponseEntity.notFound().build();
        List<Tourist> activeTourists = touristRepository.findAll().stream()
                .filter(Tourist::isActive).collect(Collectors.toList());
        List<Map<String, Object>> nearby = new ArrayList<>();
        for (Tourist t : activeTourists) {
            LocationHistory last = locationHistoryRepository
                    .findTopByTouristIdOrderByTimestampDesc(t.getTouristId());
            if (last == null) continue;
            double dist = haversine(h.getLatitude(), h.getLongitude(),
                    last.getLatitude(), last.getLongitude());
            if (dist <= h.getRadius()) {
                Map<String, Object> entry = new HashMap<>();
                entry.put("touristId", t.getTouristId());
                entry.put("name",      t.getName());
                entry.put("distanceM", Math.round(dist));
                entry.put("lastSeen",  last.getTimestamp());
                entry.put("latitude",  last.getLatitude());
                entry.put("longitude", last.getLongitude());
                nearby.add(entry);
            }
        }
        return ResponseEntity.ok(nearby);
    }

    @GetMapping("/{id}/alerts")
    public ResponseEntity<List<Alert>> getAlerts(@PathVariable Long id) {
        Hotspot h = hotspotRepository.findById(id).orElse(null);
        if (h == null) return ResponseEntity.notFound().build();
        List<Alert> all = alertRepository.findAll();
        List<Alert> nearby = new ArrayList<>();
        for (Alert a : all) {
            LocationHistory loc = locationHistoryRepository
                    .findTopByTouristIdOrderByTimestampDesc(a.getTouristId());
            if (loc == null) continue;
            double dist = haversine(h.getLatitude(), h.getLongitude(),
                    loc.getLatitude(), loc.getLongitude());
            if (dist <= h.getRadius() * 2) nearby.add(a);
        }
        nearby.sort(Comparator.comparing(Alert::getTimestamp).reversed());
        return ResponseEntity.ok(nearby.stream().limit(20).collect(Collectors.toList()));
    }

    // ── Auto-generate danger clusters ─────────────────────────────
    @PostMapping("/generate")
    public ResponseEntity<Map<String, Object>> generateClusters() {
        // Remove old auto-generated clusters
        hotspotRepository.deleteAll(hotspotRepository.findByAutoGenerated(true));

        // Gather alert locations — SKIP any with null/zero coordinates
        List<Alert> allAlerts = alertRepository.findAll();
        List<double[]> points = new ArrayList<>();

        for (Alert a : allAlerts) {
            LocationHistory loc = locationHistoryRepository
                    .findTopByTouristIdOrderByTimestampDesc(a.getTouristId());
            if (loc == null) continue;
            // Skip zero/null coordinates (unset GPS fix)
            if (Math.abs(loc.getLatitude()) < 0.001 && Math.abs(loc.getLongitude()) < 0.001) continue;
            points.add(new double[]{ loc.getLatitude(), loc.getLongitude(), a.getSeverity() });
        }

        // Grid clustering — 50m cells
        final double CELL_METRES = 50.0;
        final double DEG_PER_METRE = 1.0 / 111000.0;
        final double cellDeg = CELL_METRES * DEG_PER_METRE;

        Map<String, List<double[]>> cells = new HashMap<>();
        for (double[] p : points) {
            // Use integer grid indices (not float keys) to avoid precision issues
            long gridLat = Math.round(Math.floor(p[0] / cellDeg));
            long gridLon = Math.round(Math.floor(p[1] / cellDeg));
            String key = gridLat + "," + gridLon;
            cells.computeIfAbsent(key, k -> new ArrayList<>()).add(p);
        }

        List<Hotspot> generated = new ArrayList<>();
        int num = 1;
        for (Map.Entry<String, List<double[]>> entry : cells.entrySet()) {
            List<double[]> cluster = entry.getValue();
            if (cluster.size() < 3) continue;

            double avgLat = cluster.stream().mapToDouble(p -> p[0]).average().orElse(0);
            double avgLon = cluster.stream().mapToDouble(p -> p[1]).average().orElse(0);
            double avgSev = cluster.stream().mapToDouble(p -> p[2]).average().orElse(0);

            // Sanity check — skip if centroid is still near (0,0)
            if (Math.abs(avgLat) < 0.001 && Math.abs(avgLon) < 0.001) continue;

            Hotspot h = new Hotspot();
            h.setName("Incident Cluster #" + num++);
            h.setCategory("DANGER_CLUSTER");
            h.setLatitude(avgLat);
            h.setLongitude(avgLon);
            h.setRadius(75);
            h.setAlertCount(cluster.size());
            h.setAutoGenerated(true);
            h.setDescription(String.format(
                    "Auto-detected: %d incidents, avg severity %.0f.", cluster.size(), avgSev));
            h.setCreatedAt(LocalDateTime.now(ZoneId.of("Asia/Kolkata")));
            generated.add(h);
        }

        hotspotRepository.saveAll(generated);

        Map<String, Object> result = new HashMap<>();
        result.put("clustersGenerated", generated.size());
        result.put("alertsProcessed",   points.size());
        result.put("pointsSkipped",     allAlerts.size() - points.size());
        return ResponseEntity.ok(result);
    }

    private double haversine(double lat1, double lon1, double lat2, double lon2) {
        final double R = 6371000;
        double dLat = Math.toRadians(lat2 - lat1);
        double dLon = Math.toRadians(lon2 - lon1);
        double a = Math.sin(dLat/2) * Math.sin(dLat/2)
                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                * Math.sin(dLon/2) * Math.sin(dLon/2);
        return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    }

    // ── Reviews ───────────────────────────────────────────────────

    @GetMapping("/{id}/reviews")
    public ResponseEntity<List<HotspotReview>> getReviews(@PathVariable Long id) {
        return ResponseEntity.ok(reviewRepository.findByHotspotIdOrderByCreatedAtDesc(id));
    }

    @PostMapping("/{id}/reviews")
    public ResponseEntity<?> addReview(@PathVariable Long id, @RequestBody HotspotReview review) {
        if (review.getRating() < 1 || review.getRating() > 5)
            return ResponseEntity.badRequest().body("Rating must be 1–5");
        review.setHotspotId(id);
        return ResponseEntity.ok(reviewRepository.save(review));
    }
}
