# application-local.properties (Postgres local/dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/touristdb?stringtype=unspecified&options=-c%20TimeZone=Asia/Kolkata&sendSetTimeZone=false
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Let Hibernate create/alter schema in dev (safe option). Change to 'validate' or remove for prod.
spring.jpa.hibernate.ddl-auto=update


# Ensure Flyway runs after JPA created tables (Flyway will also manage data migration)
#spring.jpa.defer-datasource-initialization=true

# Flyway settings
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# Logging
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.data-source-properties.sendSetTimeZone=false
