import { useEffect, useState, useRef, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import maplibregl from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import {
  Plus, Trash2, Edit3, X, Check, Zap,
  MapPin, Users, AlertTriangle, Coffee, Utensils,
  Heart, Droplets, Home, Eye, RefreshCw,
  ChevronRight, Clock, Navigation, Info,
  Wifi, Star,
} from 'lucide-react'
import api from '../../lib/api'

const MAPTILER_KEY = 'jbYIDNeXWpUkQx80YgXc'

// ── Category config ───────────────────────────────────────────────
const CATEGORY = {
  VIEWPOINT:       { label: 'Viewpoint',       color: '#2979ff', icon: Eye,           markerBg: '#1a3a8f' },
  REST_STOP:       { label: 'Rest Stop',        color: '#00e5cc', icon: Coffee,        markerBg: '#0a3a38' },
  MEDICAL:         { label: 'Medical',          color: '#22c55e', icon: Heart,         markerBg: '#14532d' },
  WATER:           { label: 'Water Source',     color: '#38bdf8', icon: Droplets,      markerBg: '#0c4a6e' },
  SHELTER:         { label: 'Shelter',          color: '#a78bfa', icon: Home,          markerBg: '#3b0764' },
  FOOD_STALL:      { label: 'Food Spot',         color: '#f97316', icon: Utensils,      markerBg: '#431407' },
  DANGER_CLUSTER:  { label: 'Danger Cluster',   color: '#ef4444', icon: AlertTriangle, markerBg: '#7f1d1d' },
}

const FACILITIES_OPTIONS = [
  'Toilets', 'Parking', 'First Aid', 'Drinking Water',
  'Seating', 'Shade', 'Mobile Signal', 'WiFi', 'Food Stall', 'Emergency Phone',
]

function catColor(cat) { return CATEGORY[cat]?.color ?? '#00e5cc' }
function catLabel(cat) { return CATEGORY[cat]?.label ?? cat }
function CatIcon({ cat, size = 14 }) {
  const Icon = CATEGORY[cat]?.icon ?? MapPin
  return <Icon size={size} />
}

// ── Haversine distance (metres) ───────────────────────────────────
function haversine(lat1, lon1, lat2, lon2) {
  const R = 6371000
  const dLat = (lat2 - lat1) * Math.PI / 180
  const dLon = (lon2 - lon1) * Math.PI / 180
  const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
}

// ── Hotspot list item ─────────────────────────────────────────────
function HotspotItem({ hotspot, selected, onClick, onEdit, onDelete }) {
  const color = catColor(hotspot.category)
  const [hover, setHover] = useState(false)
  return (
    <motion.div layout initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }}
      onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)}
      style={{ borderRadius:'12px', overflow:'hidden', marginBottom:'6px', border:`1px solid ${selected ? color+'55' : hover ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,0.04)'}`, background: selected ? `${color}08` : 'transparent', transition:'all 0.15s', cursor:'pointer' }}
    >
      <div style={{ height:'2px', background: color }} />
      <div style={{ padding:'12px 14px' }} onClick={onClick}>
        <div style={{ display:'flex', alignItems:'center', gap:'8px', marginBottom:'4px' }}>
          <div style={{ width:'28px', height:'28px', flexShrink:0, borderRadius:'8px', background:`${color}18`, border:`1px solid ${color}33`, display:'flex', alignItems:'center', justifyContent:'center', color }}>
            <CatIcon cat={hotspot.category} size={13} />
          </div>
          <div style={{ flex:1, minWidth:0 }}>
            <p style={{ fontFamily:'Outfit,sans-serif', fontSize:'13px', fontWeight:'600', color:'#fff', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{hotspot.name}</p>
            <div style={{ display:'flex', alignItems:'center', gap:'6px' }}>
              <span style={{ fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'600', color, background:`${color}18`, padding:'1px 7px', borderRadius:'20px', border:`1px solid ${color}33` }}>{catLabel(hotspot.category)}</span>
              {hotspot.autoGenerated && <span style={{ fontFamily:'Inter,sans-serif', fontSize:'9px', color:'rgba(255,255,255,0.3)', background:'rgba(255,255,255,0.06)', padding:'1px 6px', borderRadius:'20px' }}>Auto</span>}
              {hotspot.alertCount > 0 && <span style={{ fontFamily:'Inter,sans-serif', fontSize:'9px', color:'#ef4444', background:'rgba(239,68,68,0.1)', padding:'1px 6px', borderRadius:'20px', display:'flex', alignItems:'center', gap:'3px' }}><AlertTriangle size={8} /> {hotspot.alertCount}</span>}
            </div>
          </div>
        </div>
        {hotspot.description && <p style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'rgba(255,255,255,0.3)', lineHeight:1.5, paddingLeft:'36px', marginTop:'4px' }}>{hotspot.description.slice(0,80)}{hotspot.description.length > 80 ? '…' : ''}</p>}
      </div>
      <AnimatePresence>
        {hover && !hotspot.autoGenerated && (
          <motion.div initial={{ opacity:0, height:0 }} animate={{ opacity:1, height:'auto' }} exit={{ opacity:0, height:0 }}
            style={{ borderTop:'1px solid rgba(255,255,255,0.04)', display:'flex', overflow:'hidden' }}
          >
            {[
              { icon:Edit3,  label:'Edit',   fn:(e)=>{ e.stopPropagation(); onEdit(hotspot) },      col:'rgba(255,255,255,0.4)' },
              { icon:Trash2, label:'Delete', fn:(e)=>{ e.stopPropagation(); onDelete(hotspot.id, hotspot.name) }, col:'#ef4444' },
            ].map(({ icon:Icon, label, fn, col }) => (
              <button key={label} onClick={fn}
                style={{ flex:1, padding:'7px', background:'none', border:'none', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:'4px', fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'600', color:col }}
                onMouseEnter={e=>e.currentTarget.style.background='rgba(255,255,255,0.05)'}
                onMouseLeave={e=>e.currentTarget.style.background='none'}
              >
                <Icon size={11} /> {label}
              </button>
            ))}
          </motion.div>
        )}
        {hover && hotspot.autoGenerated && (
          <motion.div initial={{ opacity:0, height:0 }} animate={{ opacity:1, height:'auto' }} exit={{ opacity:0, height:0 }}
            style={{ borderTop:'1px solid rgba(255,255,255,0.04)', overflow:'hidden' }}
          >
            <button onClick={(e)=>{ e.stopPropagation(); onDelete(hotspot.id, hotspot.name) }}
              style={{ width:'100%', padding:'7px', background:'none', border:'none', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:'4px', fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'600', color:'#ef4444' }}
              onMouseEnter={e=>e.currentTarget.style.background='rgba(255,255,255,0.05)'}
              onMouseLeave={e=>e.currentTarget.style.background='none'}
            >
              <Trash2 size={11} /> Delete
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  )
}

// ── Hotspot form ──────────────────────────────────────────────────
function HotspotForm({ hotspot, pendingCoords, onSave, onCancel }) {
  const [form, setForm] = useState({
    name:        hotspot?.name        ?? '',
    category:    hotspot?.category    ?? 'VIEWPOINT',
    description: hotspot?.description ?? '',
    facilities:  hotspot?.facilities  ? hotspot.facilities.split(',').filter(Boolean) : [],
    capacity:    hotspot?.capacity    ?? '',
    radius:      hotspot?.radius      ?? 100,
    latitude:    hotspot?.latitude    ?? pendingCoords?.lat ?? '',
    longitude:   hotspot?.longitude   ?? pendingCoords?.lon ?? '',
    openingTime: hotspot?.openingTime ?? '',
    closingTime: hotspot?.closingTime ?? '',
    breakStart:  hotspot?.breakStart  ?? '',
    breakEnd:    hotspot?.breakEnd    ?? '',
    openDays:    hotspot?.openDays    ?? 'Mon–Sun',
  })
  const [errors, setErrors] = useState({})

  useEffect(() => {
    if (!pendingCoords) return
    setForm(p => ({ ...p, latitude: pendingCoords.lat.toFixed(6), longitude: pendingCoords.lon.toFixed(6) }))
  }, [pendingCoords])

  function validate() {
    const e = {}
    if (!form.name.trim())   e.name = 'Required'
    if (form.latitude === '') e.lat  = 'Required'
    if (form.longitude === '') e.lon = 'Required'
    setErrors(e); return !Object.keys(e).length
  }

  function toggleFacility(f) {
    setForm(p => ({
      ...p,
      facilities: p.facilities.includes(f) ? p.facilities.filter(x => x !== f) : [...p.facilities, f],
    }))
  }

  function handleSave() {
    if (!validate()) return
    onSave({
      ...form, id: hotspot?.id,
      latitude:  parseFloat(form.latitude),
      longitude: parseFloat(form.longitude),
      radius:    parseFloat(form.radius) || 100,
      capacity:  form.capacity ? parseInt(form.capacity) : null,
      facilities: form.facilities.join(','),
    })
  }

  const inp = f => e => setForm(p => ({ ...p, [f]: e.target.value }))
  const IS = (err) => ({ width:'100%', padding:'9px 11px', borderRadius:'8px', fontSize:'12px', fontFamily:'Inter,sans-serif', color:'#fff', outline:'none', boxSizing:'border-box', background:'rgba(255,255,255,0.04)', border:`1px solid ${err ? 'rgba(239,68,68,0.5)' : 'rgba(255,255,255,0.08)'}` })
  const LS = { fontFamily:'Inter,sans-serif', fontSize:'10px', color:'rgba(0,229,204,0.7)', letterSpacing:'0.8px', textTransform:'uppercase', marginBottom:'4px', display:'block' }

  return (
    <div style={{ display:'flex', flexDirection:'column', gap:'14px', padding:'16px' }}>

      {pendingCoords && (
        <div style={{ display:'flex', alignItems:'center', gap:'8px', padding:'8px 10px', borderRadius:'8px', background:'rgba(0,229,204,0.07)', border:'1px solid rgba(0,229,204,0.2)' }}>
          <Check size={12} color="#00e5cc" />
          <span style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'#00e5cc' }}>
            Location set: {parseFloat(form.latitude).toFixed(5)}, {parseFloat(form.longitude).toFixed(5)}
          </span>
        </div>
      )}

      <div>
        <label style={LS}>Name *</label>
        <input value={form.name} onChange={inp('name')} placeholder="e.g. Echo Point Viewpoint" style={IS(errors.name)} />
        {errors.name && <p style={{ color:'#ef4444', fontSize:'10px', marginTop:'3px', fontFamily:'Inter,sans-serif' }}>{errors.name}</p>}
      </div>

      <div>
        <label style={LS}>Category *</label>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'5px' }}>
          {Object.entries(CATEGORY).filter(([k]) => k !== 'DANGER_CLUSTER').map(([key, cfg]) => (
            <button key={key} type="button" onClick={() => setForm(p => ({ ...p, category: key }))}
              style={{ padding:'8px 4px', borderRadius:'8px', cursor:'pointer', border:`1px solid ${form.category === key ? cfg.color : 'rgba(255,255,255,0.07)'}`, background: form.category === key ? `${cfg.color}22` : 'rgba(255,255,255,0.02)', fontFamily:'Inter,sans-serif', fontSize:'9px', fontWeight:'600', color: form.category === key ? cfg.color : 'rgba(255,255,255,0.3)', display:'flex', flexDirection:'column', alignItems:'center', gap:'5px', transition:'all 0.15s' }}>
              <cfg.icon size={13} />
              {cfg.label}
            </button>
          ))}
        </div>
      </div>

      <div>
        <label style={LS}>Description</label>
        <textarea value={form.description} onChange={inp('description')} placeholder="What is at this location?" rows={2} style={{ ...IS(false), resize:'vertical', lineHeight:1.5 }} />
      </div>

      <div>
        <label style={LS}>Facilities</label>
        <div style={{ display:'flex', flexWrap:'wrap', gap:'5px' }}>
          {FACILITIES_OPTIONS.map(f => {
            const active = form.facilities.includes(f)
            return (
              <button key={f} type="button" onClick={() => toggleFacility(f)}
                style={{ padding:'4px 10px', borderRadius:'20px', cursor:'pointer', fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'500', background: active ? 'rgba(0,229,204,0.12)' : 'rgba(255,255,255,0.04)', border:`1px solid ${active ? 'rgba(0,229,204,0.35)' : 'rgba(255,255,255,0.07)'}`, color: active ? '#00e5cc' : 'rgba(255,255,255,0.35)', transition:'all 0.15s' }}>
                {active && '✓ '}{f}
              </button>
            )
          })}
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'8px' }}>
        <div>
          <label style={LS}>Capacity (people)</label>
          <input value={form.capacity} onChange={inp('capacity')} type="number" placeholder="optional" style={IS(false)} />
        </div>
        <div>
          <label style={LS}>Detection Radius (m)</label>
          <input value={form.radius} onChange={inp('radius')} type="number" style={IS(false)} />
        </div>
      </div>

      {/* Operating hours */}
      <div>
        <label style={LS}>Open Days</label>
        <input value={form.openDays} onChange={inp('openDays')} placeholder="e.g. Mon–Sun or Mon–Fri" style={IS(false)} />
      </div>
      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'10px' }}>
        <div>
          <label style={LS}>Opening Time</label>
          <input value={form.openingTime} onChange={inp('openingTime')} type="time" style={IS(false)} />
        </div>
        <div>
          <label style={LS}>Closing Time</label>
          <input value={form.closingTime} onChange={inp('closingTime')} type="time" style={IS(false)} />
        </div>
        <div>
          <label style={LS}>Break Start</label>
          <input value={form.breakStart} onChange={inp('breakStart')} type="time" placeholder="optional" style={IS(false)} />
        </div>
        <div>
          <label style={LS}>Break End</label>
          <input value={form.breakEnd} onChange={inp('breakEnd')} type="time" placeholder="optional" style={IS(false)} />
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'8px' }}>
        <div>
          <label style={LS}>Latitude *</label>
          <input value={form.latitude} onChange={inp('latitude')} type="number" step="0.0001" style={IS(errors.lat)} />
        </div>
        <div>
          <label style={LS}>Longitude *</label>
          <input value={form.longitude} onChange={inp('longitude')} type="number" step="0.0001" style={IS(errors.lon)} />
        </div>
      </div>
      <p style={{ fontFamily:'Inter,sans-serif', fontSize:'10px', color:'rgba(255,255,255,0.25)', marginTop:'-8px' }}>Or click anywhere on the map to set location.</p>

      <div style={{ display:'flex', gap:'8px' }}>
        <button onClick={handleSave} style={{ flex:1, padding:'10px', borderRadius:'10px', cursor:'pointer', fontFamily:'Outfit,sans-serif', fontSize:'12px', fontWeight:'700', background:'linear-gradient(135deg,#00e5cc,#00b8a4)', border:'none', color:'#060d18' }}>
          {hotspot ? 'Save Changes' : 'Add Hotspot'}
        </button>
        <button onClick={onCancel} style={{ padding:'10px 14px', borderRadius:'10px', cursor:'pointer', fontFamily:'Inter,sans-serif', fontSize:'12px', background:'rgba(255,255,255,0.04)', border:'1px solid rgba(255,255,255,0.08)', color:'rgba(255,255,255,0.4)' }}>
          Cancel
        </button>
      </div>
    </div>
  )
}

// ── Detail panel (selected hotspot) ──────────────────────────────
function DetailPanel({ hotspot, nearbyTourists, alertHistory, onClose, onEdit, onDelete }) {
  const color = catColor(hotspot.category)
  const [tab, setTab] = useState('info')
  const facilities = hotspot.facilities ? hotspot.facilities.split(',').filter(Boolean) : []

  return (
    <motion.div initial={{ opacity:0, x:20 }} animate={{ opacity:1, x:0 }} exit={{ opacity:0, x:20 }}
      style={{ position:'absolute', top:0, right:0, bottom:0, width:'320px', background:'#0a1628', borderLeft:`1px solid ${color}33`, display:'flex', flexDirection:'column', zIndex:10 }}
    >
      {/* Header */}
      <div style={{ padding:'16px', borderBottom:`1px solid ${color}22`, flexShrink:0 }}>
        <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between', gap:'8px', marginBottom:'10px' }}>
          <div style={{ display:'flex', alignItems:'center', gap:'10px' }}>
            <div style={{ width:'36px', height:'36px', flexShrink:0, borderRadius:'10px', background:`${color}18`, border:`1px solid ${color}33`, display:'flex', alignItems:'center', justifyContent:'center', color }}>
              <CatIcon cat={hotspot.category} size={16} />
            </div>
            <div>
              <h3 style={{ fontFamily:'Outfit,sans-serif', fontSize:'15px', fontWeight:'700', color:'#fff', marginBottom:'3px' }}>{hotspot.name}</h3>
              <div style={{ display:'flex', gap:'6px', alignItems:'center' }}>
                <span style={{ fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'600', color, background:`${color}18`, padding:'2px 8px', borderRadius:'20px', border:`1px solid ${color}33` }}>{catLabel(hotspot.category)}</span>
                {hotspot.autoGenerated && <span style={{ fontFamily:'Inter,sans-serif', fontSize:'9px', color:'rgba(255,255,255,0.3)', background:'rgba(255,255,255,0.06)', padding:'2px 7px', borderRadius:'20px' }}>Auto-detected</span>}
              </div>
            </div>
          </div>
          <button onClick={onClose} style={{ background:'none', border:'none', cursor:'pointer', padding:'2px', flexShrink:0 }}><X size={14} color="rgba(255,255,255,0.3)" /></button>
        </div>

        {/* Quick stats */}
        <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'8px' }}>
          {[
            { label:'Nearby',  value: nearbyTourists?.length ?? 0,  color: '#00e5cc' },
            { label:'Alerts',  value: hotspot.alertCount || alertHistory?.length || 0, color: '#ef4444' },
            { label:'Radius',  value: `${hotspot.radius}m`,         color: 'rgba(255,255,255,0.4)' },
          ].map(s => (
            <div key={s.label} style={{ textAlign:'center', padding:'8px', borderRadius:'8px', background:'rgba(255,255,255,0.03)', border:'1px solid rgba(255,255,255,0.05)' }}>
              <p style={{ fontFamily:'Bebas Neue,sans-serif', fontSize:'20px', color:s.color, lineHeight:1 }}>{s.value}</p>
              <p style={{ fontFamily:'Inter,sans-serif', fontSize:'9px', color:'rgba(255,255,255,0.3)', textTransform:'uppercase', letterSpacing:'0.5px', marginTop:'3px' }}>{s.label}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Tabs */}
      <div style={{ display:'flex', borderBottom:'1px solid rgba(255,255,255,0.05)', flexShrink:0 }}>
        {['info','tourists','alerts'].map(t => (
          <button key={t} onClick={() => setTab(t)}
            style={{ flex:1, padding:'10px', background:'none', border:'none', borderBottom:`2px solid ${tab===t ? color : 'transparent'}`, cursor:'pointer', fontFamily:'Outfit,sans-serif', fontSize:'11px', fontWeight:'600', letterSpacing:'0.8px', textTransform:'uppercase', color: tab===t ? color : 'rgba(255,255,255,0.3)', transition:'color 0.15s' }}>
            {t}{t==='tourists' && nearbyTourists?.length > 0 ? ` (${nearbyTourists.length})` : ''}
            {t==='alerts' && (hotspot.alertCount||alertHistory?.length) > 0 ? ` (${hotspot.alertCount||alertHistory?.length})` : ''}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div style={{ flex:1, overflowY:'auto' }}>
        <AnimatePresence mode="wait">

          {tab === 'info' && (
            <motion.div key="info" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }} style={{ padding:'14px', display:'flex', flexDirection:'column', gap:'12px' }}>
              {hotspot.description && (
                <p style={{ fontFamily:'Inter,sans-serif', fontSize:'12px', color:'rgba(255,255,255,0.55)', lineHeight:1.6 }}>{hotspot.description}</p>
              )}
              <div style={{ display:'flex', flexDirection:'column', gap:'8px' }}>
                {[
                  { label:'Coordinates', value:`${hotspot.latitude?.toFixed(5)}, ${hotspot.longitude?.toFixed(5)}` },
                  { label:'Capacity',    value: hotspot.capacity ? `${hotspot.capacity} people` : '—' },
                  { label:'Radius',      value:`${hotspot.radius}m detection` },
                ].map(row => (
                  <div key={row.label} style={{ display:'flex', justifyContent:'space-between', padding:'8px 10px', borderRadius:'8px', background:'rgba(255,255,255,0.02)', border:'1px solid rgba(255,255,255,0.05)' }}>
                    <span style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'rgba(255,255,255,0.3)' }}>{row.label}</span>
                    <span style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'rgba(255,255,255,0.7)' }}>{row.value}</span>
                  </div>
                ))}
              </div>
              {facilities.length > 0 && (
                <div>
                  <p style={{ fontFamily:'Inter,sans-serif', fontSize:'10px', color:'rgba(255,255,255,0.3)', textTransform:'uppercase', letterSpacing:'0.5px', marginBottom:'8px' }}>Facilities</p>
                  <div style={{ display:'flex', flexWrap:'wrap', gap:'5px' }}>
                    {facilities.map(f => (
                      <span key={f} style={{ fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'500', color:'rgba(0,229,204,0.8)', background:'rgba(0,229,204,0.07)', padding:'3px 9px', borderRadius:'20px', border:'1px solid rgba(0,229,204,0.15)' }}>{f}</span>
                    ))}
                  </div>
                </div>
              )}
              {!hotspot.autoGenerated && (
                <div style={{ display:'flex', gap:'8px', marginTop:'4px' }}>
                  <button onClick={() => onEdit(hotspot)} style={{ flex:1, padding:'8px', borderRadius:'8px', cursor:'pointer', fontFamily:'Inter,sans-serif', fontSize:'11px', fontWeight:'600', background:'rgba(255,255,255,0.04)', border:'1px solid rgba(255,255,255,0.1)', color:'rgba(255,255,255,0.5)', display:'flex', alignItems:'center', justifyContent:'center', gap:'5px' }}>
                    <Edit3 size={11} /> Edit
                  </button>
                  <button onClick={() => onDelete(hotspot.id, hotspot.name)} style={{ flex:1, padding:'8px', borderRadius:'8px', cursor:'pointer', fontFamily:'Inter,sans-serif', fontSize:'11px', fontWeight:'600', background:'rgba(239,68,68,0.08)', border:'1px solid rgba(239,68,68,0.2)', color:'#ef4444', display:'flex', alignItems:'center', justifyContent:'center', gap:'5px' }}>
                    <Trash2 size={11} /> Delete
                  </button>
                </div>
              )}
            </motion.div>
          )}

          {tab === 'tourists' && (
            <motion.div key="tourists" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }} style={{ padding:'14px' }}>
              {!nearbyTourists?.length
                ? <div style={{ textAlign:'center', padding:'40px 0' }}>
                    <Users size={24} color="rgba(255,255,255,0.1)" style={{ margin:'0 auto 10px' }} />
                    <p style={{ fontFamily:'Inter,sans-serif', fontSize:'12px', color:'rgba(255,255,255,0.2)' }}>No tourists currently nearby</p>
                  </div>
                : nearbyTourists.map(t => (
                    <div key={t.touristId} style={{ padding:'10px 12px', borderRadius:'10px', background:'rgba(0,229,204,0.05)', border:'1px solid rgba(0,229,204,0.1)', marginBottom:'7px' }}>
                      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:'4px' }}>
                        <span style={{ fontFamily:'Outfit,sans-serif', fontSize:'12px', fontWeight:'600', color:'#fff' }}>{t.name}</span>
                        <span style={{ fontFamily:'JetBrains Mono,monospace', fontSize:'10px', color:'rgba(0,229,204,0.6)', background:'rgba(0,229,204,0.08)', padding:'1px 6px', borderRadius:'4px' }}>{t.touristId}</span>
                      </div>
                      <div style={{ display:'flex', gap:'12px' }}>
                        <span style={{ fontFamily:'Inter,sans-serif', fontSize:'10px', color:'rgba(255,255,255,0.4)', display:'flex', alignItems:'center', gap:'3px' }}>
                          <Navigation size={9} /> {t.distanceM}m away
                        </span>
                        <span style={{ fontFamily:'Inter,sans-serif', fontSize:'10px', color:'rgba(255,255,255,0.3)', display:'flex', alignItems:'center', gap:'3px' }}>
                          <Clock size={9} /> {t.lastSeen ? new Date(t.lastSeen + '+05:30').toLocaleTimeString('en-IN', { hour:'2-digit', minute:'2-digit', hour12:true }) : '—'}
                        </span>
                      </div>
                    </div>
                  ))
              }
            </motion.div>
          )}

          {tab === 'alerts' && (
            <motion.div key="alerts" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }} style={{ padding:'14px' }}>
              {!alertHistory?.length
                ? <div style={{ textAlign:'center', padding:'40px 0' }}>
                    <AlertTriangle size={24} color="rgba(255,255,255,0.1)" style={{ margin:'0 auto 10px' }} />
                    <p style={{ fontFamily:'Inter,sans-serif', fontSize:'12px', color:'rgba(255,255,255,0.2)' }}>No alert history near this hotspot</p>
                  </div>
                : alertHistory.map(a => {
                    const colors = { FALL:'#c0392b', SOS:'#c0392b', CRITICAL:'#c0392b', HIGH:'#d4a843', MEDIUM:'#d4a843', OVERDUE:'#d4a843', ZONE:'#2979ff' }
                    const col = colors[a.type?.toUpperCase()] || '#2979ff'
                    return (
                      <div key={a.id} style={{ padding:'9px 12px', borderRadius:'9px', background:`${col}11`, border:`1px solid ${col}33`, borderLeft:`2px solid ${col}`, marginBottom:'7px' }}>
                        <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:'4px' }}>
                          <span style={{ fontFamily:'Outfit,sans-serif', fontSize:'10px', fontWeight:'700', color:col, letterSpacing:'1px' }}>{a.type}</span>
                          <span style={{ fontFamily:'JetBrains Mono,monospace', fontSize:'9px', color:'rgba(255,255,255,0.3)' }}>{a.touristId}</span>
                        </div>
                        <p style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'rgba(255,255,255,0.6)', lineHeight:1.5 }}>{a.message}</p>
                      </div>
                    )
                  })
              }
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  )
}

// ── Main page ─────────────────────────────────────────────────────
export default function AdminHotspots() {
  const mapRef      = useRef(null)
  const mapInstance = useRef(null)
  const markersRef  = useRef({})
  const mapReadyRef = useRef(false)
  const panelRef    = useRef('list')   // mirrors panel state — readable inside map callbacks

  const [hotspots,       setHotspots]       = useState([])
  const [loading,        setLoading]        = useState(true)
  const [mapReady,       setMapReady]       = useState(false)
  const [selected,       setSelected]       = useState(null)
  const [nearbyTourists, setNearbyTourists] = useState(null)
  const [alertHistory,   setAlertHistory]   = useState(null)
  const [panel,          setPanel]          = useState('list')
  const [editHotspot,    setEditHotspot]    = useState(null)
  const [pendingCoords,  setPendingCoords]  = useState(null)
  const [filterCat,      setFilterCat]      = useState('all')
  const [generating,     setGenerating]     = useState(false)
  const [genResult,      setGenResult]      = useState(null)
  const [sidebarOpen,    setSidebarOpen]    = useState(true)   // collapsible sidebar
  const hotspotsRef = useRef([])

  // Keep panelRef in sync so map click handler always sees current panel
  useEffect(() => { panelRef.current = panel }, [panel])
  const loadHotspots = useCallback(() => {
    api.get('/hotspots').then(r => { setHotspots(r.data); hotspotsRef.current = r.data })
      .catch(console.error).finally(() => setLoading(false))
  }, [])

  useEffect(() => { loadHotspots() }, [loadHotspots])

  // Load detail data when selected changes
  useEffect(() => {
    if (!selected) { setNearbyTourists(null); setAlertHistory(null); return }
    api.get(`/hotspots/${selected.id}/nearby-tourists`).then(r => setNearbyTourists(r.data)).catch(() => setNearbyTourists([]))
    api.get(`/hotspots/${selected.id}/alerts`).then(r => setAlertHistory(r.data)).catch(() => setAlertHistory([]))
  }, [selected])

  // ── Map init ──────────────────────────────────────────────────
  useEffect(() => {
    if (!mapRef.current || mapInstance.current) return
    const map = new maplibregl.Map({
      container: mapRef.current,
      style: `https://api.maptiler.com/maps/dataviz-dark/style.json?key=${MAPTILER_KEY}`,
      center: [77.0595, 10.0889], zoom: 12, pitch: 30,
    })
    map.addControl(new maplibregl.NavigationControl(), 'bottom-right')
    map.on('load', () => {
      map.addSource('terrain', { type:'raster-dem', url:`https://api.maptiler.com/tiles/terrain-rgb/tiles.json?key=${MAPTILER_KEY}`, tileSize:256 })
      map.setTerrain({ source:'terrain', exaggeration:1.2 })
      mapInstance.current = map
      mapReadyRef.current = true
      setMapReady(true)
      renderMarkers(hotspotsRef.current)
    })

    // Click on map to set hotspot location — use panelRef to avoid stale closure
    map.on('click', (e) => {
      if (panelRef.current === 'create' || panelRef.current === 'edit') {
        setPendingCoords({ lat: e.lngLat.lat, lon: e.lngLat.lng })
      }
    })

    return () => { map.remove(); mapInstance.current = null; mapReadyRef.current = false }
  }, [])

  // Re-render markers when hotspots or filter changes
  useEffect(() => {
    if (mapReady) renderMarkers(hotspots)
  }, [hotspots, filterCat, mapReady])

  // ── Render map markers ────────────────────────────────────────
  // SVG pin: 40×52px, coordinate tip at bottom-center (20, 52). No CSS transforms.
  function makePinSVG(color, bg, iconPathD) {
    // Teardrop shape as actual SVG path — matches original CSS teardrop look exactly
    // 30×38px: teardrop head is a circle at (15,15) r=14, pointed bottom at (15,38)
    // No CSS rotation = no phantom bounding box = anchor:'bottom' is pixel-perfect
    const el = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
    el.setAttribute('width', '30')
    el.setAttribute('height', '38')
    el.setAttribute('viewBox', '0 0 30 38')
    el.style.cssText = 'display:block;overflow:visible;'
    el.innerHTML = `
      <path d="M15 38 C15 38 1 24 1 15 A14 14 0 1 1 29 15 C29 24 15 38 15 38Z"
            fill="${bg}" stroke="${color}" stroke-width="1.2" opacity="0.72"/>
      <g transform="translate(3,3) scale(1)">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="1.75"
             stroke-linecap="round" stroke-linejoin="round" opacity="0.78">
          ${iconPathD}
        </svg>
      </g>
    `
    return el
  }

  function makeDangerSVG(color, bg, alertCount = 0) {
    const el = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
    el.setAttribute('width', '30')
    el.setAttribute('height', '30')
    el.setAttribute('viewBox', '0 0 30 30')
    el.style.cssText = 'display:block;overflow:visible;'
    const badge = alertCount > 0
      ? `<circle cx="23" cy="7" r="6" fill="#ef4444" stroke="#0a1628" stroke-width="1.2"/>
         <text x="23" y="11" text-anchor="middle" font-family="Inter,sans-serif" font-size="7" font-weight="700" fill="#fff">${alertCount > 9 ? '9+' : alertCount}</text>`
      : ''
    el.innerHTML = `
      <circle cx="15" cy="15" r="13" fill="${bg}" stroke="${color}" stroke-width="1.2" opacity="0.72"/>
      <g transform="translate(3,3)">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="1.75"
             stroke-linecap="round" stroke-linejoin="round" opacity="0.78">
          <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/>
          <line x1="12" y1="9" x2="12" y2="13"/>
          <circle cx="12" cy="17" r="0.5" fill="${color}"/>
        </svg>
      </g>
      ${badge}
    `
    return el
  }

  function renderMarkers(list) {
    const map = mapInstance.current
    if (!map) return

    Object.values(markersRef.current).forEach(m => m.remove())
    markersRef.current = {}

    const visible = filterCat === 'all' ? list : list.filter(h => h.category === filterCat)

    visible.forEach(hotspot => {
      const color = catColor(hotspot.category)
      const cfg   = CATEGORY[hotspot.category] ?? CATEGORY.VIEWPOINT
      const isDanger = hotspot.category === 'DANGER_CLUSTER'

      const el = document.createElement('div')
      el.style.cssText = 'cursor:pointer;'
      el.appendChild(isDanger
        ? makeDangerSVG(color, cfg.markerBg, hotspot.alertCount ?? 0)
        : makePinSVG(color, cfg.markerBg, getIconPath(hotspot.category))
      )

      el.addEventListener('click', (e) => {
        e.stopPropagation()
        const h = hotspotsRef.current.find(x => x.id === hotspot.id) ?? hotspot
        setSelected(prev => prev?.id === h.id ? null : h)
        setPanel('list')
        map.flyTo({ center:[hotspot.longitude, hotspot.latitude], zoom:15, duration:700 })
      })

      markersRef.current[hotspot.id] = new maplibregl.Marker({ element: el, anchor: isDanger ? 'center' : 'bottom' })
        .setLngLat([hotspot.longitude, hotspot.latitude])
        .addTo(map)
    })

    // Add pulse keyframe once
    if (!document.getElementById('hotspot-styles')) {
      const s = document.createElement('style'); s.id = 'hotspot-styles'
      s.textContent = `@keyframes hotPulse{0%{transform:scale(1);opacity:.7}100%{transform:scale(2.2);opacity:0}}`
      document.head.appendChild(s)
    }
  }

  // SVG path strings for each category icon
  function getIconPath(cat) {
    switch(cat) {
      case 'VIEWPOINT':  return '<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>'
      case 'REST_STOP':  return '<path d="M17 8h1a4 4 0 0 1 0 8h-1"/><path d="M3 8h14v9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V8z"/><path d="M6 2c0 1.5 1.5 2 1.5 3.5S6 7 6 8"/><path d="M10 2c0 1.5 1.5 2 1.5 3.5S10 7 10 8"/><path d="M14 2c0 1.5 1.5 2 1.5 3.5S14 7 14 8"/>'
      case 'MEDICAL':    return '<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>'
      case 'WATER':      return '<path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"/>'
      case 'SHELTER':    return '<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>'
      case 'FOOD_STALL': return '<path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><line x1="7" y1="2" x2="7" y2="22"/><path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3v5"/>'
      default:           return '<circle cx="12" cy="12" r="10"/>'
    }
  }

  // ── CRUD ──────────────────────────────────────────────────────
  async function handleSave(data) {
    if (data.id) await api.put(`/hotspots/${data.id}`, data)
    else         await api.post('/hotspots', data)
    loadHotspots(); setPanel('list'); setEditHotspot(null); setPendingCoords(null)
  }

  async function handleDelete(id, name) {
    if (!window.confirm(`Delete "${name}"?`)) return
    await api.delete(`/hotspots/${id}`)
    if (selected?.id === id) setSelected(null)
    loadHotspots()
  }

  async function handleGenerate() {
    setGenerating(true); setGenResult(null)
    try {
      const r = await api.post('/hotspots/generate')
      setGenResult(r.data)
      loadHotspots()
    } catch { setGenResult({ error: true }) }
    finally { setGenerating(false) }
    setTimeout(() => setGenResult(null), 5000)
  }

  const filtered = filterCat === 'all' ? hotspots : hotspots.filter(h => h.category === filterCat)
  const counts   = Object.keys(CATEGORY).reduce((acc, cat) => {
    acc[cat] = hotspots.filter(h => h.category === cat).length
    return acc
  }, {})

  return (
    <div style={{ height:'100%', display:'flex', overflow:'hidden', position:'relative' }}>

      {/* ── Sidebar ───────────────────────────────────────────── */}
      <AnimatePresence initial={false}>
        {sidebarOpen && (
          <motion.div
            key="sidebar"
            initial={{ width: 0, opacity: 0 }}
            animate={{ width: 300, opacity: 1 }}
            exit={{ width: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            style={{ flexShrink:0, display:'flex', flexDirection:'column', background:'#0a1628', borderRight:'1px solid rgba(0,229,204,0.07)', overflow:'hidden' }}
          >

        {/* Header */}
        <div style={{ padding:'16px', borderBottom:'1px solid rgba(0,229,204,0.07)', flexShrink:0 }}>
          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:'12px' }}>
            <div>
              <h2 style={{ fontFamily:'Outfit,sans-serif', fontSize:'16px', fontWeight:'700', color:'#fff', marginBottom:'2px' }}>Hotspots</h2>
              <p style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'rgba(255,255,255,0.3)' }}>{hotspots.length} total · {hotspots.filter(h=>h.category==='DANGER_CLUSTER').length} danger clusters</p>
            </div>
            <div style={{ display:'flex', gap:'6px' }}>
              {/* Generate clusters */}
              <button onClick={handleGenerate} disabled={generating} title="Auto-detect danger clusters from alert data"
                style={{ padding:'7px 9px', borderRadius:'8px', cursor: generating ? 'not-allowed' : 'pointer', background:'rgba(239,68,68,0.1)', border:'1px solid rgba(239,68,68,0.25)', color:'#ef4444', display:'flex', alignItems:'center', gap:'4px', fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'600' }}>
                {generating ? <RefreshCw size={12} style={{ animation:'spin 1s linear infinite' }} /> : <Zap size={12} />}
                {generating ? '' : 'Clusters'}
              </button>
              {/* Add hotspot */}
              <button onClick={() => { setPanel(p => p==='create' ? 'list' : 'create'); setEditHotspot(null); setPendingCoords(null) }}
                style={{ padding:'7px 10px', borderRadius:'8px', cursor:'pointer', background: panel==='create' ? 'rgba(0,229,204,0.15)' : 'linear-gradient(135deg,#00e5cc,#00b8a4)', border:'none', color: panel==='create' ? '#00e5cc' : '#060d18', display:'flex', alignItems:'center', gap:'5px', fontFamily:'Inter,sans-serif', fontSize:'11px', fontWeight:'600' }}>
                <Plus size={13} /> Add
              </button>
            </div>
          </div>

          {/* Generate result banner */}
          <AnimatePresence>
            {genResult && (
              <motion.div initial={{ opacity:0, height:0 }} animate={{ opacity:1, height:'auto' }} exit={{ opacity:0, height:0 }}
                style={{ marginBottom:'10px', overflow:'hidden' }}
              >
                <div style={{ padding:'8px 10px', borderRadius:'8px', background: genResult.error ? 'rgba(239,68,68,0.1)' : 'rgba(0,229,204,0.08)', border:`1px solid ${genResult.error ? 'rgba(239,68,68,0.3)' : 'rgba(0,229,204,0.2)'}`, fontFamily:'Inter,sans-serif', fontSize:'11px', color: genResult.error ? '#ef4444' : '#00e5cc' }}>
                  {genResult.error ? 'Generation failed' : `✓ Generated ${genResult.clustersGenerated} clusters from ${genResult.alertsProcessed} alerts`}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Category filter */}
          <div style={{ display:'flex', gap:'4px', flexWrap:'wrap' }}>
            <button onClick={() => setFilterCat('all')} style={{ padding:'3px 9px', borderRadius:'20px', cursor:'pointer', fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'500', background: filterCat==='all' ? 'rgba(0,229,204,0.12)' : 'rgba(255,255,255,0.04)', border:`1px solid ${filterCat==='all' ? 'rgba(0,229,204,0.3)' : 'rgba(255,255,255,0.06)'}`, color: filterCat==='all' ? '#00e5cc' : 'rgba(255,255,255,0.3)' }}>All</button>
            {Object.entries(CATEGORY).map(([key, cfg]) => (
              <button key={key} onClick={() => setFilterCat(key)}
                style={{ padding:'3px 9px', borderRadius:'20px', cursor:'pointer', fontFamily:'Inter,sans-serif', fontSize:'10px', fontWeight:'500', background: filterCat===key ? `${cfg.color}22` : 'rgba(255,255,255,0.04)', border:`1px solid ${filterCat===key ? cfg.color+'55' : 'rgba(255,255,255,0.06)'}`, color: filterCat===key ? cfg.color : 'rgba(255,255,255,0.3)', display:'flex', alignItems:'center', gap:'4px' }}>
                {counts[key] > 0 && <span>{counts[key]}</span>} {cfg.label}
              </button>
            ))}
          </div>
        </div>

        {/* Panel */}
        <div style={{ flex:1, overflowY:'auto' }}>
          <AnimatePresence mode="wait">

            {(panel === 'create' || panel === 'edit') && (
              <motion.div key="form" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }}>
                <div style={{ padding:'10px 14px 0', borderBottom:'1px solid rgba(255,255,255,0.04)' }}>
                  <p style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'rgba(255,255,255,0.35)', marginBottom:'8px' }}>
                    {pendingCoords ? '✓ Location set from map' : 'Click anywhere on the map to set location, or enter coordinates manually.'}
                  </p>
                </div>
                <HotspotForm
                  hotspot={editHotspot}
                  pendingCoords={pendingCoords}
                  onSave={handleSave}
                  onCancel={() => { setPanel('list'); setEditHotspot(null); setPendingCoords(null) }}
                />
              </motion.div>
            )}

            {panel === 'list' && (
              <motion.div key="list" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }} style={{ padding:'10px' }}>
                {loading
                  ? <p style={{ textAlign:'center', padding:'40px', fontFamily:'Inter,sans-serif', fontSize:'12px', color:'rgba(255,255,255,0.2)' }}>Loading...</p>
                  : filtered.length === 0
                  ? <div style={{ textAlign:'center', padding:'40px 0' }}>
                      <MapPin size={24} color="rgba(0,229,204,0.12)" style={{ margin:'0 auto 10px' }} />
                      <p style={{ fontFamily:'Inter,sans-serif', fontSize:'12px', color:'rgba(255,255,255,0.2)' }}>No hotspots yet</p>
                      <p style={{ fontFamily:'Inter,sans-serif', fontSize:'11px', color:'rgba(255,255,255,0.15)', marginTop:'6px' }}>Add one manually or click "Clusters" to auto-detect</p>
                    </div>
                  : filtered.map(h => (
                      <HotspotItem key={h.id} hotspot={h} selected={selected?.id===h.id}
                        onClick={() => {
                          setSelected(prev => prev?.id===h.id ? null : h)
                          if (mapInstance.current) mapInstance.current.flyTo({ center:[h.longitude, h.latitude], zoom:15, duration:700 })
                        }}
                        onEdit={h => { setEditHotspot(h); setPanel('edit') }}
                        onDelete={handleDelete}
                      />
                    ))
                }
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Legend */}
        <div style={{ padding:'10px 14px', borderTop:'1px solid rgba(0,229,204,0.06)', flexShrink:0, display:'flex', gap:'8px', flexWrap:'wrap' }}>
          {Object.entries(CATEGORY).map(([key, cfg]) => (
            <div key={key} style={{ display:'flex', alignItems:'center', gap:'4px' }}>
              <div style={{ width:'7px', height:'7px', borderRadius:'50%', background:cfg.color }} />
              <span style={{ fontFamily:'Inter,sans-serif', fontSize:'9px', color:'rgba(255,255,255,0.3)' }}>{cfg.label}</span>
            </div>
          ))}
        </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Sidebar collapse tab — always visible on left edge of map */}
      <button
        onClick={() => setSidebarOpen(o => !o)}
        style={{ position:'absolute', left: sidebarOpen ? '300px' : '0px', top:'50%', transform:'translateY(-50%)', zIndex:20, width:'18px', height:'48px', background:'#0a1628', border:'1px solid rgba(0,229,204,0.15)', borderLeft: sidebarOpen ? 'none' : '1px solid rgba(0,229,204,0.15)', borderRadius: sidebarOpen ? '0 6px 6px 0' : '0 6px 6px 0', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', color:'rgba(0,229,204,0.5)', transition:'left 0.2s' }}
      >
        <ChevronRight size={11} style={{ transform: sidebarOpen ? 'rotate(180deg)' : 'none', transition:'transform 0.2s' }} />
      </button>

      {/* ── Map area ─────────────────────────────────────────────── */}
      <div style={{ flex:1, position:'relative' }}>
        <div ref={mapRef} style={{ width:'100%', height:'100%', cursor: (panel==='create'||panel==='edit') ? 'crosshair' : 'default' }} />

        {/* Create-mode hint */}
        {(panel === 'create' || panel === 'edit') && !pendingCoords && (
          <div style={{ position:'absolute', top:'16px', left:'50%', transform:'translateX(-50%)', background:'rgba(0,229,204,0.95)', color:'#060d18', padding:'8px 18px', borderRadius:'20px', fontFamily:'Outfit,sans-serif', fontSize:'12px', fontWeight:'700', pointerEvents:'none', boxShadow:'0 4px 20px rgba(0,229,204,0.35)', zIndex:10 }}>
            Click on the map to set hotspot location
          </div>
        )}

        {/* Detail panel */}
        <AnimatePresence>
          {selected && panel === 'list' && (
            <DetailPanel
              hotspot={selected}
              nearbyTourists={nearbyTourists}
              alertHistory={alertHistory}
              onClose={() => setSelected(null)}
              onEdit={h => { setEditHotspot(h); setPanel('edit') }}
              onDelete={handleDelete}
            />
          )}
        </AnimatePresence>
      </div>

      <style>{`@keyframes spin{from{transform:rotate(0)}to{transform:rotate(360deg)}}`}</style>
    </div>
  )
}