package com.safety.repository;

import com.safety.model.Hotspot;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface HotspotRepository extends JpaRepository<Hotspot, Long> {

    List<Hotspot> findByCategory(String category);

    // Find all auto-generated hotspots (for re-generation cleanup)
    List<Hotspot> findByAutoGenerated(boolean autoGenerated);

    // Find hotspots within rough bounding box (pre-filter before precise haversine)
    @Query("SELECT h FROM Hotspot h WHERE " +
            "h.latitude  BETWEEN :minLat AND :maxLat AND " +
            "h.longitude BETWEEN :minLon AND :maxLon")
    List<Hotspot> findInBoundingBox(
            @Param("minLat") double minLat, @Param("maxLat") double maxLat,
            @Param("minLon") double minLon, @Param("maxLon") double maxLon
    );
}
